from .nodes.backbone_nodes import (
    HollyBlueprintBuildNode,
    HollyBlueprintInspectNode,
    HollyBundleInspectNode,
    HollyHistoryFilterNode,
    HollyHistoryHitsInspectNode,
    HollyHistoryRetrieveNode,
    HollyInputBundleNode,
    HollyIntegrityValidateNode,
    HollyIntentAnalyzeNode,
    HollyIntentInspectNode,
    HollyModelFormatterNode,
    HollyPreferenceProfileNode,
    HollyProfileInspectNode,
    HollyPromptCompareNode,
    HollyReusablePatternsInspectNode,
    HollySemanticsInspectNode,
    HollySemanticExpandNode,
    HollySessionViewerNode,
    HollyStrategyInspectNode,
    HollyStrategySelectNode,
    HollyTraceSaveNode,
)
from .nodes.prompt_nodes import PromptPrefixNode, PromptWithImageTagsNode

NODE_CLASS_MAPPINGS = {
    "PromptPrefixNode": PromptPrefixNode,
    "PromptWithImageTagsNode": PromptWithImageTagsNode,
    "HollyInputBundleNode": HollyInputBundleNode,
    "HollyIntentAnalyzeNode": HollyIntentAnalyzeNode,
    "HollySemanticExpandNode": HollySemanticExpandNode,
    "HollyIntegrityValidateNode": HollyIntegrityValidateNode,
    "HollyStrategySelectNode": HollyStrategySelectNode,
    "HollyBlueprintBuildNode": HollyBlueprintBuildNode,
    "HollyModelFormatterNode": HollyModelFormatterNode,
    "HollyPromptCompareNode": HollyPromptCompareNode,
    "HollyTraceSaveNode": HollyTraceSaveNode,
    "HollyHistoryRetrieveNode": HollyHistoryRetrieveNode,
    "HollyPreferenceProfileNode": HollyPreferenceProfileNode,
    "HollyHistoryFilterNode": HollyHistoryFilterNode,
    "HollySessionViewerNode": HollySessionViewerNode,
    "HollyBundleInspectNode": HollyBundleInspectNode,
    "HollyIntentInspectNode": HollyIntentInspectNode,
    "HollySemanticsInspectNode": HollySemanticsInspectNode,
    "HollyStrategyInspectNode": HollyStrategyInspectNode,
    "HollyBlueprintInspectNode": HollyBlueprintInspectNode,
    "HollyHistoryHitsInspectNode": HollyHistoryHitsInspectNode,
    "HollyProfileInspectNode": HollyProfileInspectNode,
    "HollyReusablePatternsInspectNode": HollyReusablePatternsInspectNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "PromptPrefixNode": "Prompt Prefix",
    "PromptWithImageTagsNode": "Prompt + Image Tags",
    "HollyInputBundleNode": "Holly Input Bundle",
    "HollyIntentAnalyzeNode": "Holly Intent Analyze",
    "HollySemanticExpandNode": "Holly Semantic Expand",
    "HollyIntegrityValidateNode": "Holly Integrity Validate",
    "HollyStrategySelectNode": "Holly Strategy Select",
    "HollyBlueprintBuildNode": "Holly Blueprint Build",
    "HollyModelFormatterNode": "Holly Model Formatter",
    "HollyPromptCompareNode": "Holly Prompt Compare",
    "HollyTraceSaveNode": "Holly Trace Save",
    "HollyHistoryRetrieveNode": "Holly History Retrieve",
    "HollyPreferenceProfileNode": "Holly Preference Profile",
    "HollyHistoryFilterNode": "Holly History Filter",
    "HollySessionViewerNode": "Holly Session Viewer",
    "HollyBundleInspectNode": "Holly Bundle Inspect",
    "HollyIntentInspectNode": "Holly Intent Inspect",
    "HollySemanticsInspectNode": "Holly Semantics Inspect",
    "HollyStrategyInspectNode": "Holly Strategy Inspect",
    "HollyBlueprintInspectNode": "Holly Blueprint Inspect",
    "HollyHistoryHitsInspectNode": "Holly History Hits Inspect",
    "HollyProfileInspectNode": "Holly Profile Inspect",
    "HollyReusablePatternsInspectNode": "Holly Reusable Patterns Inspect",
}

